version: 3

project:
  locator: SolaceProducts_solace-connector-kafka-sink
  id: SolaceProducts_solace-connector-kafka-sink
  name: solace-connector-kafka-sink
  teams: []
  labels:
    - java

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"

paths:
  exclude:
    - ./.git
    - ./.github

telemetry:
  scope: full
